export const patients = [
  {
    id: "pt_jason",
    name: "Jason M.",
    age: 22,
    injury: "ACL / Meniscus",
    stage: "Early Motion",
    phaseNum: 2,
    carePath: "post-op",
    surgeryDate: "2026-03-01",
    weekPostOp: 14,
    pain: 2,
    rom: "0-118",
    ptNote: "Full extension restored. Keep monitoring swelling after longer walking days.",
    assignedProvider: "Dr. Valade, PT",
    goal: "Return to basketball and lifting",
    homeEquipment: "Resistance bands, step, light dumbbells",
    visitFrequency: "2x/week",
    avatar: "JM",
    assignedExercises: ["e1", "e2", "e3", "e4", "e5"],
  },
  {
    id: "pt_sara",
    name: "Sara K.",
    age: 31,
    injury: "Patellar Tendon",
    stage: "Strengthening",
    phaseNum: 3,
    carePath: "non-surgical",
    surgeryDate: "",
    weekPostOp: 22,
    pain: 3,
    rom: "0-135",
    ptNote: "Responding well to slow tempo loading. Keep symptoms under 3/10 after sessions.",
    assignedProvider: "Morgan Lee, ATC",
    goal: "Run pain-free and return to pickleball",
    homeEquipment: "Decline board, dumbbell, resistance band",
    visitFrequency: "1x/week",
    avatar: "SK",
    assignedExercises: ["e19", "e20", "e21"],
  },
  {
    id: "pt_mike",
    name: "Mike T.",
    age: 26,
    injury: "Achilles",
    stage: "Protection",
    phaseNum: 1,
    carePath: "post-op",
    surgeryDate: "2026-05-03",
    weekPostOp: 5,
    pain: 4,
    rom: "Limited",
    ptNote: "Prioritize symptom control and gentle ankle motion before progressing calf loading.",
    assignedProvider: "Alex Rivera, PTA",
    goal: "Walk normally and return to recreational soccer",
    homeEquipment: "Towel, step, resistance band",
    visitFrequency: "2x/week",
    avatar: "MT",
    assignedExercises: ["e24"],
  },
];

export const reports = [
  {
    id: "r1",
    patientId: "pt_sara",
    ts: Date.now() - 1000 * 60 * 18,
    exercise: "Bulgarian Split Squat",
    swelling: 2,
    pain: 3,
    location: "Below kneecap",
    note: "Felt sharp pulling during the descent phase",
    ptRead: false,
    ptReply: null,
  },
  {
    id: "r2",
    patientId: "pt_jason",
    ts: Date.now() - 1000 * 60 * 60 * 2,
    exercise: "Terminal Knee Extension",
    swelling: 1,
    pain: 2,
    location: "Lateral knee",
    note: "Minor ache that went away after warmup",
    ptRead: true,
    ptReply:
      "Good sign that it resolved with warmup — keep the load light and ice post-session. We'll check ROM Thursday.",
  },
];

export const initialMessages = [
  {
    id: "msg-0",
    patientId: "pt_jason",
    sender: "assistant",
    text: "What's up Jason. Checked your session data — wall slides look solid. What do you need today?",
    ts: Date.now() - 1000 * 60 * 60 * 3,
  },
  {
    id: "msg-1",
    patientId: "pt_jason",
    sender: "patient",
    text: "Keep today lighter if swelling shows up after the heel slides.",
    ts: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: "msg-2",
    patientId: "pt_sara",
    sender: "patient",
    text: "Can I swap split squats for wall sits today? Tendon feels cranky.",
    ts: Date.now() - 1000 * 60 * 42,
  },
];

export const exercises = [
  {
    id: "e1",
    name: "Quad Sets",
    injuries: ["ACL / Meniscus"],
    stages: ["Protection", "Early Motion"],
    muscles: "Quadriceps",
    sets: 3,
    reps: "15",
    rest: "60s",
    equipment: "None",
    cue: "Tighten quad while leg is flat. Hold 5s. Keep kneecap pulled upward.",
    difficulty: 1,
  },
  {
    id: "e4",
    name: "Terminal Knee Extension",
    injuries: ["ACL / Meniscus"],
    stages: ["Early Motion", "Strengthening", "Prehab"],
    muscles: "Vastus Medialis, Quadriceps",
    sets: 3,
    reps: "15",
    rest: "60s",
    equipment: "Resistance band",
    cue: "Band behind knee. Drive knee to full extension. Pause 1s, then control return.",
    difficulty: 2,
  },
  {
    id: "e8",
    name: "Lateral Band Walks",
    injuries: ["ACL / Meniscus", "Patellar Tendon", "Ankle Sprain"],
    stages: ["Strengthening", "Return to Sport", "Prehab"],
    muscles: "Glute Med, Hip Abductors",
    sets: 3,
    reps: "20 steps",
    rest: "60s",
    equipment: "Resistance band",
    cue: "Band above knees or ankles. Slight squat. Keep toes forward and pelvis level.",
    difficulty: 2,
  },
];

export const milestones = [
  {
    id: "acl-prehab-control",
    injury: "ACL / Meniscus",
    phaseNum: 0,
    stage: "Prehab",
    title: "Baseline Movement Screen",
    details:
      "Document baseline range of motion, swelling, gait, and single-leg control before surgery or higher-load training.",
  },
  {
    id: "acl-full-extension",
    injury: "ACL / Meniscus",
    phaseNum: 1,
    stage: "Protection",
    title: "Full Knee Extension",
    details:
      "Restore full knee extension, quiet swelling, and comfortable heel-prop or prone-hang tolerance.",
  },
  {
    id: "acl-quad-control",
    injury: "ACL / Meniscus",
    phaseNum: 2,
    stage: "Early Motion",
    title: "Quad Control and Normal Gait",
    details:
      "Straight-leg raise without lag, improving flexion, and walking pattern without major compensation.",
  },
];
