insert into public.exercises (
  name,
  muscles,
  equipment,
  cue,
  description,
  difficulty,
  youtube_url,
  reminder,
  instructions,
  clinical_notes,
  rest
) values
  (
    'Step-Ups',
    'Quad, Glute, VMO',
    'Step box',
    'Drive through whole foot. Keep knee over 2nd toe. Control the lowering phase.',
    'Controlled step-up pattern for lower-extremity strength and knee tracking.',
    3,
    'https://www.youtube.com/watch?v=g9ibq3NFXyQ',
    'Use a lower step if symptoms or mechanics change.',
    'Step onto a low box through the whole foot, pause tall, then lower with control.',
    'Watch for knee cave, hip drop, or pushing off the back leg.',
    '90s'
  ),
  (
    'Single-Leg Romanian Deadlift Reach',
    'Hamstring, Glute, Foot/Ankle Stabilizers',
    'None / Dumbbell',
    'Hinge at hip. Keep pelvis square. Reach long through back leg.',
    'Single-leg hinge drill for posterior-chain strength and balance control.',
    3,
    'https://www.youtube.com/watch?v=zteT9sVYOSM',
    'Quality matters more than depth.',
    'Stand on one leg, hinge at the hip, reach the free leg back, then return tall with control.',
    'Keep pelvis level and avoid twisting through the trunk.',
    '90s'
  ),
  (
    'Single-Leg Balance',
    'Ankle Stabilizers, Glute Med, Proprioception',
    'None / Foam pad',
    'Start on firm ground. Progress to foam, eyes closed, or ball toss.',
    'Balance drill for proprioception and single-leg control.',
    2,
    'https://www.youtube.com/watch?v=7SF7AYh2_Yw',
    'Stay near support if balance feels uncertain.',
    'Stand on one leg with light fingertip support available. Keep hips level and hold steady.',
    'Progress only when the foot, knee, and hip stay quiet.',
    '30s'
  ),
  (
    'Drop Landing Mechanics',
    'Quad, Glute, Calf, Coordination',
    'Low box',
    'Step off, land softly, knees over toes, hips back. Stick landing for 2s.',
    'Low-level landing drill for return-to-impact mechanics.',
    3,
    'https://www.youtube.com/watch?v=10k5ojDdnAo',
    'Stop if landing causes sharp pain or swelling response.',
    'Step off a low box, land softly with hips back, and hold the landing position for two seconds.',
    'Use only when symptoms are quiet and basic strength work is tolerated.',
    '90s'
  ),
  (
    'Isometric Knee Extension',
    'Quad',
    'None / Machine',
    'Hold at a comfortable knee angle. Push hard but keep pain tolerable.',
    'Patellar tendon isometric loading drill for pain modulation and quad activation.',
    1,
    'https://www.youtube.com/watch?v=9WoINw8UVbg',
    'Keep tendon pain tolerable and steady.',
    'Set a comfortable knee angle and push into resistance without moving the joint.',
    'Useful early when isotonic loading is too irritable.',
    '2 min'
  ),
  (
    'Spanish Squat - Isometric',
    'Quad, Patellar Tendon',
    'Rope/strap',
    'Strap behind knees. Sit back with vertical shins. Keep trunk upright.',
    'Patellar tendon isometric squat variation with reduced forward knee travel.',
    2,
    'https://www.youtube.com/watch?v=mik90mAS6fU',
    'Hold strong, but avoid sharp tendon pain.',
    'Place a strap behind the knees, sit back into a squat with vertical shins, and hold.',
    'Monitor symptoms during the hold and again the next morning.',
    '2 min'
  ),
  (
    'Decline Eccentric Squat',
    'Quad, Patellar Tendon',
    'Decline board',
    'Lower over 3-4s. Use pain-monitoring rules. Avoid bouncing or deep collapse.',
    'Slow eccentric squat for progressive patellar tendon loading.',
    3,
    'https://www.youtube.com/watch?v=EsNA-yq6KWY',
    'Keep pain tolerable and avoid bouncing.',
    'Stand on a decline board and lower slowly over three to four seconds before returning with control.',
    'Use after isometrics are tolerated and swelling is not increasing.',
    '90s'
  ),
  (
    'Heavy Slow Goblet Squat',
    'Quad, Glute, Tendon Capacity',
    'Dumbbell / Kettlebell',
    'Slow 3s down, controlled up. Use tolerable load and pain-free depth when needed.',
    'Heavy slow resistance pattern for quad and tendon capacity.',
    3,
    'https://www.youtube.com/watch?v=7-80HiXX1K8',
    'Load should feel controlled, not provocative.',
    'Hold a weight at the chest, lower slowly, pause briefly, and stand with control.',
    'Progress load gradually when symptoms stay stable after sessions.',
    '2 min'
  ),
  (
    'Bulgarian Split Squat',
    'Quad, Glute',
    'Bench',
    'Rear foot elevated. Front knee tracks toes. Keep pelvis level.',
    'Single-leg strength exercise for quad and hip capacity.',
    3,
    'https://www.youtube.com/watch?v=WqLCAIA4gGU',
    'Start shallow if tendon symptoms are sensitive.',
    'Place the rear foot on a bench, lower under control, and drive through the front foot.',
    'Keep pelvis level and knee tracking over the toes.',
    '2 min'
  ),
  (
    'Pogo Hops',
    'Calf, Quad, Tendon Elasticity',
    'None',
    'Small quick hops. Stay tall. Stop if tendon pain increases after session.',
    'Low-amplitude hopping drill for tendon elasticity and return-to-impact preparation.',
    3,
    'https://www.youtube.com/watch?v=zwsRYtR6KiM',
    'Stop if tendon pain increases after the session.',
    'Perform small quick hops with a tall posture and quiet contacts.',
    'Use only after strength work is tolerated without symptom flare.',
    '90s'
  ),
  (
    'Plyometric Bounding',
    'Quad, Glute, Calf, Hamstring',
    'None',
    'Exaggerated running stride. Land controlled. Build distance gradually.',
    'Bounding drill for later-stage power and running preparation.',
    4,
    'https://www.youtube.com/watch?v=wc1BquWW18c',
    'Build distance gradually and keep landings controlled.',
    'Use long controlled bounds, landing softly and maintaining alignment.',
    'Reserve for later-stage return work with stable symptoms.',
    '2 min'
  ),
  (
    'Ankle Pumps',
    'Calf, Anterior Tibialis',
    'None',
    'Pump foot up and down through comfortable range. Keep motion smooth.',
    'Early ankle motion drill for Achilles and ankle mobility.',
    1,
    'https://www.youtube.com/watch?v=n6HI30C00Bk',
    'Keep motion comfortable and smooth.',
    'Move the foot up and down through a comfortable range without forcing end range.',
    'Use as gentle circulation and mobility work early in the plan.',
    '45s'
  ),
  (
    'Towel Calf Stretch',
    'Gastrocnemius, Soleus',
    'Towel/band',
    'Pull forefoot toward shin. Do knee straight and knee bent versions.',
    'Gentle calf stretch for gastrocnemius and soleus mobility.',
    1,
    'https://www.youtube.com/watch?v=dINlxZithDU',
    'Stretch gently; do not force tendon pain.',
    'Loop a towel around the forefoot and draw the foot toward the shin with the knee straight and bent.',
    'Keep the stretch mild if Achilles symptoms are irritable.',
    '30s'
  ),
  (
    'Bent-Knee Soleus Raise',
    'Soleus, Achilles',
    'Dumbbell / Machine',
    'Knee bent around 60-90 degrees. Lift heel slowly and lower under control.',
    'Bent-knee calf raise emphasizing soleus and Achilles capacity.',
    3,
    'https://www.youtube.com/watch?v=vzg233ClYdU',
    'Use slow tempo and tolerable load.',
    'With the knee bent, lift the heel slowly, pause at the top, and lower with control.',
    'Important for Achilles plans before faster elastic work.',
    '90s'
  ),
  (
    'Single-Leg Eccentric Calf Raise',
    'Achilles, Gastrocnemius, Soleus',
    'Step',
    'Rise with two legs, lower on one over 3s. Keep pain tolerable, not sharp.',
    'Eccentric calf loading drill for Achilles tendon strength.',
    3,
    'https://www.youtube.com/watch?v=NCPXdrr56ZI',
    'Tolerable tendon discomfort is okay; sharp pain is not.',
    'Rise with both legs, shift to one leg, and lower slowly over three seconds.',
    'Progress volume only if symptoms stay settled the next day.',
    '90s'
  ),
  (
    'Farmer Carry on Toes',
    'Calf, Foot Intrinsics, Core',
    'Dumbbells',
    'Walk tall on balls of feet. Keep ankles steady and steps controlled.',
    'Loaded carry variation for calf endurance, foot control, and trunk stiffness.',
    3,
    'https://www.youtube.com/watch?v=4Ly1EMfJk6Y',
    'Keep steps controlled and ankles steady.',
    'Hold weights at the sides and walk tall on the balls of the feet.',
    'Use after basic calf raises are tolerated.',
    '90s'
  ),
  (
    'Hopping Progression',
    'Achilles, Calf, Foot',
    'None',
    'Start bilateral, then single-leg, then forward/back and side-to-side hops.',
    'Progressive hopping sequence for Achilles return-to-impact work.',
    4,
    'https://www.youtube.com/watch?v=7yNCqSJ1Qpk',
    'Progress one variation at a time.',
    'Start with bilateral hops, then progress to single-leg and directional variations as tolerated.',
    'Use only when calf strength and symptoms are ready for elastic loading.',
    '2 min'
  ),
  (
    'Dynamic Warm-Up Flow',
    'Full Lower Body',
    'None',
    'Include leg swings, hip openers, skips, lunges, and gradual build-up movement.',
    'General movement preparation flow for lower-body training sessions.',
    2,
    'https://www.youtube.com/watch?v=EtbyY48FT2s',
    'Keep the warm-up easy and smooth.',
    'Move through leg swings, hip openers, skips, lunges, and gradual build-up movement.',
    'Use as a general preparation block before strength or return-to-run work.',
    'None'
  ),
  (
    'Farmer Carry',
    'Grip, Shoulder Stabilizers, Core, Hips',
    'Dumbbells / Kettlebells',
    'Walk tall with ribs down. Do not lean or let shoulders shrug.',
    'Loaded carry for trunk control, grip, and general capacity.',
    3,
    'https://www.youtube.com/watch?v=4Ly1EMfJk6Y',
    'Use a load you can carry with clean posture.',
    'Hold weights at the sides and walk tall without leaning or shrugging.',
    'Useful general strength work when a specific injury path is not selected.',
    '90s'
  )
on conflict (name) do update set
  muscles = excluded.muscles,
  equipment = excluded.equipment,
  cue = excluded.cue,
  description = excluded.description,
  difficulty = excluded.difficulty,
  youtube_url = excluded.youtube_url,
  reminder = excluded.reminder,
  instructions = excluded.instructions,
  clinical_notes = excluded.clinical_notes,
  rest = excluded.rest;
